#SITE CONFIGURATION

title: Madison Drace
description: Musician-Musicologist
repository: "andrewstiefel/music-portfolio"
baseurl: 
url: "https://md23r.github.io/music-portfolio/"

google_tag_manager: GTM-P7PZFVP

# SEO PLUGIN

social:
  name: Madison Drace
  links:
    - https://bsky.app/profile/8bitaria.bsky.social
    - https://www.instagram.com/8bit_aria
    - https://www.youtube.com/@madisondrace/
    - https://www.linkedin.com/in/madison-drace/
    - https://www.madisondrace.com
    
#THEME SETTINGS

navigation: # Navigation links
  - {name: 'Music', link: '/music'}
  - {name: 'Recordings', link: '/recordings'}
  - {name: 'Contact', link: '/contact'}
  
email: andrew@andrewstiefel.com
twitter_username: andrewstiefel
github_username: andrewstiefel
instagram_username: andrewstiefel
facebook_username: andrewstiefel
linkedin_username: andrewstiefel

#BUILD SETTINGS

markdown: kramdown
include: ['_pages']
permalink: /blog/:title

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

compress_html:
  clippings: all

plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag
